apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    generation: 1
    labels:
      run: cheers
    name: cheers
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: cheers
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: cheers
      spec:
        containers:
        - env:
          - name: EXO_4
            value: '''1'''
          image: kanedafromparis/cheers:0.0.2
          imagePullPolicy: IfNotPresent
          name: cheers
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: cheers
    name: cheers
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 32477
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      run: cheers
    sessionAffinity: None
    type: NodePort
