apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: rs
  name: rs
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rs
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: rs
    spec:
      containers:
      - image: kanedafromparis/resourcesmonger:1.0
        imagePullPolicy: IfNotPresent
        name: rs
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30