apiVersion: batch/v1
kind: Job
metadata:
  labels:
    run: pwgen
  name: pwgen
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  #  selector:
  #    matchLabels:
  #      controller-uid: 
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: pwgen
        run: pwgen
    spec:
      containers:
      - args:
        - -y
        - "22"
        - "20"
        image: kanedafromparis/pwgen:0.1
        imagePullPolicy: IfNotPresent
        name: pwgen
        resources: {}
        stdin: true
        stdinOnce: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5
