apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "upgrade to version 2.0"
  labels:
    run: logs
  name: logs
spec:
  replicas: 5
  selector:
    matchLabels:
      run: logs
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: logs
    spec:
      containers:
      - image: kanedafromparis/logversion:2.0
        imagePullPolicy: IfNotPresent
        name: logs
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5